openapi: 3.0.0
info:
  title: SmartMemo API
  version: '1.0.0'
  description: SmartMemoのAPI仕様書

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth/authorize
          tokenUrl: https://example.com/oauth/token
          scopes:
            access: メモの読み取りおよび書き込み権限

  schemas:
    Memo:
      type: object
      properties:
        id:
          type: integer
        content:
          type: string
        tags:
          type: array
          items:
            type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Tag: 
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

security:
  - OAuth2:
      - access

paths:
  /memos:
    get:
      summary: 自分のメモの一覧を取得
      operationId: getMyMemos
      tags:
        - memos
      security:
        - OAuth2:
            - access
      responses:
        '200':
          description: 自分のメモの一覧取得に成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './schemas/Memos.yml#/Memos/Memo'
                    
    post:
      summary: 自分の書いた内容からタグのおすすめをAIから取得
      operationId: suggestTagsFromAI
      tags:
        - memos
      security:
        - OAuth2:
            - access
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/Memos.yml#/Memos/PostToAI'
      responses:
        '200':
          description: タグのおすすめの取得に成功
          content:
            application/json:
              schema:
                type: object
                $ref: './schemas/Memos.yml#/Memos/SuggestedFromAI'
  /memos/create:
    post:
      summary: メモを作成
      operationId: createMemo
      tags:
        - memos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: './schemas/Memos.yml#/Memos/Memo'
      responses:
        '201':
          description: メモ作成に成功
          content:
            application/json:
              schema:
                $ref: './schemas/Memos.yml#/Memos/Memo'
  /memos/{id}:
    get:
      summary: 特定のメモを取得
      operationId: getMemoById
      tags:
        - memos
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      security:
        - OAuth2:
            - access
      responses:
        '200':
          description: メモの取得に成功
          content:
            application/json:
              schema:
                $ref: './schemas/Memos.yml#/Memos/Memo'
        '404':
          description: メモが見つからない

    patch:
      summary: メモを更新
      operationId: updateMemo
      tags:
        - memos
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      security:
        - OAuth2:
            - access
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/Memos.yml#/Memos/Memo'
      responses:
        '200':
          description: メモの変更に成功
          content:
            application/json:
              schema:
                $ref: './schemas/Memos.yml#/Memos/Memo'
        '404':
          description: メモが見つからない

    delete:
      summary: メモを削除
      operationId: deleteMemo
      tags:
        - memos
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      security:
        - OAuth2:
            - access
      responses:
        '204':
          description: メモの削除に成功
        '404':
          description: メモが見つからない

  /tags:
    get:
      summary: タグの一覧を取得
      operationId: getTags
      tags:
        - tags
      security:
        - OAuth2:
            - access
      responses:
        '200':
          description: タグの一覧取得に成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './schemas/Tags.yml#/Tags/Tag'
    post:
      summary: 新しいタグを作成
      operationId: createTag
      tags:
        - tags
      security:
        - OAuth2:
            - access
      requestBody:
        description: 新しいタグのデータ
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/Tags.yml#/Tags/PostTag'
      responses:
        '201':
          description: タグの作成に成功
          content:
            application/json:
              schema:
                $ref: './schemas/Tags.yml#/Tags/Tag'
                
  /tags/{id}:
    patch:
      summary: タグを更新
      operationId: updateTag
      tags:
        - tags
      security:
        - OAuth2:
            - access
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: 更新するタグのデータ
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tag'
      responses:
        '200':
          description: タグの更新に成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
    delete:
      summary: タグを削除
      operationId: deleteTag
      tags:
        - tags
      security:
        - OAuth2:
            - access
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: タグの削除に成功
