import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import { MemoMaker } from "@/components/memo-maker"
import MemoList from "@/components/memo-list";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased w-[100vw] h-[100vh]"
      >

        <SidebarProvider>
          <AppSidebar />
          <main className="h-[100vh] w-[100vw] flex flex-col gap-y-10">
            <SidebarTrigger />
            <div className="w-[80%] h-[80%] flex flex-col mx-auto gap-y-5">
              <MemoMaker />
              <MemoList />
              { children }
            </div>
          </main>
        </SidebarProvider>
        
      </body>
    </html>
  );
}