import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import { TextEditor } from "@/components/text-editor"
import { GoogleOAuthProvider, useGoogleLogin } from '@react-oauth/google';
import { api, GOOGLE_CLIENT_ID } from '@/utils/index';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID}>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <SidebarProvider>
          <AppSidebar />
          <main>
            <SidebarTrigger />
            {/*
            TextEditor -> テキストエリアのコンポーネント(の予定)
            これを含んで実行したらエラーが発生。
            <TextEditor />
            */
            <TextEditor />
            }
            { children }
          </main>
        </SidebarProvider>
        
      </body>
    </html>
    </GoogleOAuthProvider>
  );
}