=begin
SmartMemo API

SmartMemoのAPI仕様書

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class TagsController < ApplicationController
  def create
    @tag = Tag.create(user_id: @user_id, name: params[:name])

    render json: @tag.as_json(only: [ :id, :name ])
  end

  def destroy
    Tag.find(params[:id]).destroy

    render json: { "message" => "yes, it worked" }, status: 200
  end

  def index
    # Your code here
    @tags = User.find(@user_id).tags
    render json: @tags.as_json(only: [ :id, :name ])
  end

  def update
    Tag.find(params[:id]).update(name: params[:name])
    @tag = Tag.find(params[:id])
    render json: @tag.as_json(only: [ :id, :name ])
  end
end
