import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/globals.css";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import { TextEditor } from "@/components/text-editor"
import MemoComponent from "@/components/MemoComponent";
import { SignInButton } from '@/components/sign-in-bottun'

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({

  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      
        

        <SidebarProvider>
          <AppSidebar />
          <main className="ml-5 mt-5 gap-y-5 flex flex-col">
            <SidebarTrigger />
            <MemoComponent />
            {children}
          </main>
        </SidebarProvider>

      </body>
    </html>
  );
}