name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
        
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Set up PostgreSQL
        env:
          RAILS_ENV: test
          DB_NAME: test_db
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          DB_HOST: localhost
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          
          bin/rails db:create
          bin/rails db:schema:load

      - name: Run RSpec
        env:
          RAILS_ENV: test
          DB_NAME: test_db
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          DB_HOST: localhost
        run: |
          bundle exec rspec
